各モデルの正規表現・バリデーション機能実装
Yasunori-aloha/tenkue-board-r015 pull request #2
Opened 2020-12-21 14:24 UTC by Yasunori-aloha

## 概要
* `Userモデル・Postモデル・Commentモデル`のバリデーションの設定と確認のためのテストコードを実装する。

## 変更点
* `Userモデル`に下記のバリデーションを実装。
メールアドレスに全角文字が含まれていないこと
パスワードは8文字以上32文字以下であること
パスワードは半角英字と半角数字のいずれとも含まれていること

* `Postモデル`に下記のバリデーションを実装。
投稿内容がnot null
投稿内容は140文字以内

* `Commentモデル`に下記のバリデーションを実装。
コメント内容がnot null
コメント内容は140文字以内

* 実装したバリデーションが機能するかどうかを確認するため、各モデルのテストコードを実装。
※テストコード内の変数の作成には`FactoryBot`及び`Faker`を使用。

## テスト結果とテスト項目
- [x] 実装した各モデルのテストコードを実行し、正常終了を確認。

2020-12-22 03:27 UTC, sdkk1 requested changes
コメント箇所の修正をお願いします！コメントの主旨が分からないようでしたら、おっしゃってください！！

2020-12-22 03:27 UTC, sdkk1 commented on app/models/comment.rb
> +
user_idとpost_idが存在することを確認するバリデーションを追加してください。

2020-12-22 03:27 UTC, sdkk1 commented on app/models/post.rb
> +
user_idが存在することを確認するバリデーションを追加してください

2020-12-22 03:27 UTC, sdkk1 commented on app/models/post.rb
> +  has_many :comments
postが削除されたら、それに紐づくcommentsも削除されるようにしてください。

2020-12-22 03:27 UTC, sdkk1 commented on app/models/user.rb
> +  has_many :comments
userが削除されたら、それに紐づくpostsとcommentsも削除されるようにしてください。

2020-12-22 03:27 UTC, sdkk1 commented on db/schema.rb
> +    t.bigint "post_id"
null: falseを追加してください。

2020-12-22 03:27 UTC, sdkk1 commented on db/schema.rb
> +    t.bigint "user_id"
null: falseを追加してください。

2020-12-22 03:27 UTC, sdkk1 commented on spec/models/comment_spec.rb
> +        expect(comment.errors.full_messages).to include "Comment is too long (maximum is 140 characters)"
必須要件に「エラーメッセージを表示、日本語化」とあるので、
エラーメッセージを日本語にして、テストも日本語で行ってください。
（同上）

2020-12-22 03:27 UTC, sdkk1 commented on spec/models/comment_spec.rb
> +
「user_idがなければ無効な状態であること」、「post_idがなければ無効な状態であること」
この２つのテストも追加してください。

2020-12-22 03:27 UTC, sdkk1 commented on spec/models/post_spec.rb
> +
「user_idがなければ無効な状態であること」
このテストも追加してください。

2020-12-22 03:27 UTC, sdkk1 commented on spec/models/post_spec.rb
> +        expect(post.errors.full_messages).to include "Content is too long (maximum is 140 characters)"
必須要件に「エラーメッセージを表示、日本語化」とあるので、
エラーメッセージを日本語にして、テストも日本語で行ってください。
（同上）

2020-12-22 03:27 UTC, sdkk1 commented on spec/models/users.rb
> +        expect(user.errors.full_messages).to include "Password confirmation doesn't match Password"
必須要件に「エラーメッセージを表示、日本語化」とあるので、
エラーメッセージを日本語にして、テストも日本語で行ってください。
（同上）

2020-12-22 03:27 UTC, sdkk1 commented on app/models/user.rb
> +    validates :email, format: { with: /\A[\x01-\x7E]+\z/ }
emailの型に合わせたバリデーションを設定してください。
（例えば、test@test.comならOKになるようなバリデーションを正規表現で設定する）

2020-12-22 06:03 UTC, Yasunori-aloha commented
指摘箇所を全て修正しました
再度確認をお願いします！

2020-12-22 14:08 UTC, sdkk1 reviewed
１箇所だけ懸念点がありますので、念のため追加しておいて頂けるとありがたいです！

2020-12-22 14:08 UTC, sdkk1 commented on config/locales/models/ja.yml
> +        post_id: 投稿
これだけだと全てのエラーメッセージが日本語になっていないような気がします。（間違っていたらすみません）
modelの翻訳はこのファイルで良いと思いますので、このファイルはこのままにしておいて、追加で
https://pikawaka.com/rails/i18n#%E5%BF%9C%E7%94%A8%E7%9A%84%E3%81%AA%E4%BD%BF%E3%81%84%E6%96%B9
こちらのサイトで紹介されているように、
https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/ja.yml
このGitHubの翻訳テンプレートを入れておけば間違いないと思います。

2020-12-22 14:19 UTC, Yasunori-aloha commented on config/locales/models/ja.yml
> +        post_id: 投稿
指摘箇所の修正しました。
`ja.yml`が複数できてしまうのは避けたかったので、モデルの日本語化と同じファイルに新たに記述し、ファイルの場所も変更しました。

再度確認をお願いします。

2020-12-22 14:26 UTC, sdkk1 approved these changes
修正ありがとうございました！LGTMです！

2020-12-23 01:34 UTC, katsuokaisao commented on app/models/user.rb
> +    validates :email, format: { with: /\A[\x01-\x7E][\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: { case_sensitive: true }
細かい話にはなりますが、[a-z\d\-.]の部分の/dで0-9を省略していて次の行では0-9を使っているのが統一感をなくしてしまうと思いました。同じように/wとa-zA-z0-9もどちらかに統一した方がいいかもです。

2020-12-23 01:39 UTC, katsuokaisao commented on app/models/user.rb
> +    validates :password, format: { with: /\A(?=.*[0-9])(?=.*[a-zA-Z])([a-zA-z0-9]{8,32})\z/ }, confirmation: true
自分の理解が追いついていない部分もあるのですが、(?=.*[0-9])(?=.*[a-zA-Z])は(?=.*[/w])に置き換えることはできませんか？もし、間違っていたらすみません。

2020-12-23 02:01 UTC, katsuokaisao commented on db/migrate/20201221140510_create_posts.rb
> +      t.text       :content, null: false, default: ""
validationでpresence: trueに設定されていて、null: falseにも設定されているので、default: ""はいらないかなと思いました。お時間があれば修正した方がいいかもです。

2020-12-23 02:19 UTC, Yasunori-aloha commented
指摘のあったバリデーションを統一する様に修正しました。
`(?=.[0-9])(?=.[a-zA-Z])`の部分を`(?=.*[/w])`に変更してしまうと、`半角英字・半角数字それぞれ最低1文字`から`半角英数字が最低1文字`という制限に変わったしまうため、そのままにしています。

再度確認をお願いします。

2020-12-23 02:24 UTC, katsuokaisao reviewed
すみませんが、何点かコメントさせていただきました。確認よろしくお願い致します！

2020-12-23 02:27 UTC, katsuokaisao commented
> 指摘のあったバリデーションを統一する様に修正しました。
> `(?=.[0-9])(?=.[a-zA-Z])`の部分を`(?=.*[/w])`に変更してしまうと、`半角英字・半角数字それぞれ最低1文字`から`半角英数字が最低1文字`という制限に変わったしまうため、そのままにしています。
> 
> 再度確認をお願いします。

2020-12-23 04:41 UTC, katsuokaisao approved these changes
御対応いただきありがとうございます。LGTMです！

2020-12-23 07:45 UTC, sew-sou19 requested changes
レビュー完了しましたー！
ご確認と修正をお願いします！

2020-12-23 07:45 UTC, sew-sou19 commented on app/models/post.rb
> +    validates :user_id
ここは不要ですね！
`belongs_to :user`でnilを許可しないバリデーションが定義されてるはずなので！もし明確な理由があればレスお願いしますー！

2020-12-23 07:45 UTC, sew-sou19 commented on app/models/comment.rb
> +    validates :user_id, :post_id
ここも不要ですね！
`belongs_to :user`でnilを許可しないバリデーションが定義されてるはずなので！もし明確な理由があればレスお願いしますー！

2020-12-23 07:45 UTC, sew-sou19 commented on db/migrate/20201221140510_create_posts.rb
> +      t.text       :content, null: false, default: ""
おっしゃる通りですね！
`, default: ""`は不要だと思います。

2020-12-23 07:45 UTC, sew-sou19 commented on db/migrate/20201221140510_create_posts.rb
> +      t.text       :content, null: false, default: ""
```suggestion
      t.text       :content, null: false
```

2020-12-23 07:45 UTC, sew-sou19 commented on db/migrate/20201221141259_create_comments.rb
> +      t.text       :comment, null: false, default: ""
ここも同じですねー！
```suggestion
      t.text       :comment, null: false
```

2020-12-23 07:45 UTC, sew-sou19 commented on spec/models/user_spec.rb
> +      end
これだとパスワードが8文字の時のテストしかできていないので、32文字の時のテストも行いましょうー！

制約を付けた場合は、その閾値の前後でのテストを行うのが丁寧です！

2020-12-23 07:46 UTC, sew-sou19 commented
また、テストが通っていることのスクショも載せてください！（テスト実行後のターミナルなどの画像）

2020-12-23 09:54 UTC, Yasunori-aloha commented
指摘箇所の修正実施しました。
テストコード実行した際のスクリーンショットも添付します。

再度確認をお願いします！

<img width="469" alt="スクリーンショット 2020-12-23 18 50 46" src="https://user-images.githubusercontent.com/70802846/102983974-38f1c100-4550-11eb-91ec-d7c15fd48a3d.png">

2020-12-23 12:04 UTC, sew-sou19 approved these changes
LGTMですー！

2020-12-23 12:17 UTC, sew-sou19 approved these changes

2020-12-23 12:23 UTC, merged

2020-12-24 05:47 UTC, sdkk1 commented on app/models/post.rb
> +    validates :user_id
https://pikawaka.com/rails/validation#%E5%A4%96%E9%83%A8%E3%82%AD%E3%83%BC%E3%81%AE%E3%83%90%E3%83%AA%E3%83%87%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3

本当ですね！これは知りませんでした。勉強になります！！