掲示板一覧表示機能
Yasunori-aloha/tenkue-board-r015 pull request #4
Opened 2020-12-23 14:01 UTC by katsuokaisao

掲示板一覧表示機能を作成いたしましたので、御確認のほどよろしくお願いします！

https://i.gyazo.com/93c90312c23b9d83d8ea528a7d532890.gif

2020-12-23 15:31 UTC, Yasunori-aloha reviewed
コード確認し、何点かコメントしましたので確認をお願いします！

ページネーションに関しては、Trello敵には別タブですが機能も問題はないかと思いますのでそのままで大丈夫かと思います！

2020-12-23 15:31 UTC, Yasunori-aloha commented on config/routes.rb
> +  resources :posts,  except: [:index]
今回使用しているアクションがindexアクションだけですので、後々必要な処理でも使用していない内は記述しない方がいい気がします。

2020-12-23 15:31 UTC, Yasunori-aloha commented on app/controllers/application_controller.rb
> +            devise_parameter_sanitizer.permit(:account_update,keys:[:name,:email])
deviseではemailカラム・passwordカラムは最初から用意されているカラムですので、ストロングパラメーターで必要なカラム名は`nameカラム`だけかと思われます。

2020-12-24 11:48 UTC, sdkk1 approved these changes
私はLGTMです！（やすのりさんからの指摘事項は確認してください）
１箇所だけ、コメントしていますが、修正する必要はないと思うので、
確認だけお願いします！！

2020-12-24 11:48 UTC, sdkk1 commented on app/controllers/posts_controller.rb
> +    @posts = Post.preload(:user).page(params[:page]).per(5).order(created_at: :desc)
個人的には、サービスのUXを考慮するならば、order(updated_at: :desc)の方がいい気はします。
ただ、この共同開発の成果物を確認すると、order(created_at: :desc)になっているので、
特段修正の必要はないかと思いますが、念のため申し伝えさせてもらいました。

2020-12-24 22:50 UTC, katsuokaisao commented on app/controllers/posts_controller.rb
> +    @posts = Post.preload(:user).page(params[:page]).per(5).order(created_at: :desc)
了解いたしました。ご指摘頂きありがとうございます。

2020-12-24 23:02 UTC, katsuokaisao commented on config/routes.rb
> +  resources :posts,  except: [:index]
了解致しました！

2020-12-24 23:02 UTC, katsuokaisao commented on app/controllers/application_controller.rb
> +            devise_parameter_sanitizer.permit(:account_update,keys:[:name,:email])
確かにその通りですね。ありがとうございます。

2020-12-24 23:13 UTC, katsuokaisao commented
ご指摘いただきありがとうございました！修正を加えたので再度ご確認のほどよろしくお願い致します！！

2020-12-25 04:29 UTC, Yasunori-aloha commented
修正箇所確認しました！
LGTMです！

2020-12-25 04:30 UTC, Yasunori-aloha approved these changes

2020-12-25 06:00 UTC, sew-sou19 requested changes
レベル高いですね！
細かい部分を少しだけご確認ください！

2020-12-25 06:00 UTC, masato-sa93 commented on app/views/posts/index.html.erb
> +      <%# 未投稿の場合は「まだ投稿されたスレッドはありません。」と表示するように条件分岐すること %>
細かいですが、不要なコメントは削除しましょうー！

2020-12-25 06:00 UTC, masato-sa93 commented on config/routes.rb
> +  root to: 'posts#index'
rootパスは最上部に持ってくるのがベターです！

2020-12-25 06:39 UTC, katsuokaisao commented
壮さん、ご指摘いただきありがとうございました！修正を加えたので再度ご確認のほどよろしくお願い致します！！

2020-12-25 07:07 UTC, sew-sou19 approved these changes
LGTMですー！

2020-12-25 07:22 UTC, merged