ゲストログイン機能
Yasunori-aloha/tenkue-board-r015 pull request #5
Opened 2020-12-25 11:58 UTC by sdkk1

### 【概要】
・アカウントの新規登録をせずともワンクリックでゲストとして全機能を使用できる

### 【主な変更点】
・ヘッダーに「ゲストログイン」を含むユーザー機能のリンクを設置する
・ゲストユーザーとして、新規ユーザー登録を行わずにログインできる
・ゲストユーザーのメールアドレス・パスワードが変更できないように制限

### 【テスト結果とテスト項目】
https://gyazo.com/033ea7f47dca5c470a4b14dbb7d38efe
ゲストログインが出来ることを目視確認した。

2020-12-25 13:10 UTC, Yasunori-aloha requested changes
コード確認して、コメントしました！
また、初めて`ゲストログインボタン`を選択した際にテストユーザーが生成されますが、`sessions_controller.rb`の`SecureRandom.urlsafe_base64`で生成される文字列`- _`ある為、バリデーションで引っ掛かりユーザー作成できない状況がありました。

`seed.rb`にゲストユーザーの情報を追記してしまうか、`Userモデル`のバリデーションに記号も含ませる様に修正が必要だと思われます。
バリデーションに関しては、最初の段階で対応できていませんでした...すみません。

2020-12-25 13:10 UTC, Yasunori-aloha commented on app/controllers/users/passwords_controller.rb
> +  end
条件分岐内の処理が`registrations_controller.rb`と同じなので、条件分岐の部分をORで記述して`application_controller.rb`に移動してしまっても大丈夫だと思います。

2020-12-25 13:10 UTC, Yasunori-aloha commented on app/views/templates/_header.html.erb
> +          <span>ユーザー名 さん</span>
ユーザー名が初期値のままですので、ログインしたユーザー名が表示される様に修正をお願いします。

2020-12-25 14:16 UTC, sdkk1 commented on app/controllers/users/passwords_controller.rb
> +  end
application_controller.rbにまとめました！

2020-12-25 14:17 UTC, sdkk1 commented on app/views/templates/_header.html.erb
> +          <span>ユーザー名 さん</span>
ユーザー名が表示されるように変更しました！

2020-12-25 14:23 UTC, sdkk1 commented
ご指摘の箇所を修正しましたので、再度ご確認をお願いします！

ちなみに、ゲストユーザーのパスワード生成については、
`SecureRandom.alphanumeric`で「A-Z, a-z, 0-9 からなる文字列」が返されるので、
そのように仕様変更しました。
これで、バリデーションにかかることはないと思います！

2020-12-25 14:29 UTC, Yasunori-aloha commented
修正分のコード確認しました！
LGTMです！！

2020-12-25 14:29 UTC, Yasunori-aloha approved these changes

2020-12-26 00:12 UTC, katsuokaisao commented
LGTMです！

2020-12-26 00:13 UTC, katsuokaisao approved these changes

2020-12-26 04:14 UTC, sew-sou19 approved these changes
コードの内容は素晴らしいです！
ただ、一部注意点を記載したのでご確認お願いしますー！

2020-12-26 04:14 UTC, sew-sou19 commented on Gemfile.lock
> +    actioncable (5.2.4.4)
ここおそらく`bundle update`されましたかね、、、？
`bundle update`はオプションつけずにやると全てのgemのバージョンを上げてしまうので、他の方の環境でエラーを起こす可能性があるので気をつけましょう。

基本的には`bundle update`は必要がない限りは実行しないです。

2020-12-26 04:14 UTC, sew-sou19 commented on Gemfile
> +gem 'mini_racer', platforms: :ruby
おそらく`Could not find a JavaScript runtime.`このエラーは、Node.jsがインストールされてないからっぽいですね。gemでも対応可能ですが、他の人の環境でエラーが出ないかご注意くださいー！

2020-12-26 05:17 UTC, sdkk1 commented on Gemfile.lock
> +    actioncable (5.2.4.4)
こちら、`bundle update`をオプションつけずに実行してしまいました・・・。

実行した経緯としては、
Rspecのテストを走らせた時に、
`2020-12-24 16:30:36 WARN Selenium [DEPRECATION] Selenium::WebDriver::Chrome#driver_path= is deprecated. Use Selenium::WebDriver::Chrome::Service#driver_path= instead.`
という警告が出ていたので、
https://techtechmedia.com/chrome-web-driver/
こちらの記事を参考にして、
`gem 'chromedriver-helper'`　→　`gem 'webdrivers', '~> 3.0'`
としたのですが、
その時に`bundle install`を実行しようとしたら、
`bundle update`を実行するようにエラーが出たためでした。

以後、気をつけます。

2020-12-26 05:20 UTC, sdkk1 commented on Gemfile
> +gem 'mini_racer', platforms: :ruby
そうだったんですね！ご指摘ありがとうございます！

2020-12-26 05:20 UTC, merged