掲示板編集／削除機能
Yasunori-aloha/tenkue-board-r015 pull request #9
Opened 2020-12-29 04:48 UTC by katsuokaisao

##概要
* 掲示板編集・削除機能の実装を行った。

## 変更点
- [x] 投稿内容を変更することができる
- [x] 掲示板を削除することができる
- [x] 掲示板を編集・削除できるのは投稿者のみ
- [x] 投稿者だけが編集ページに遷移できる
- [x] 新規投稿時と同じUIで編集機能を実装している
- [x] 編集画面を開いた時点で、既に登録されている投稿内容が表示されている
- [x] 投稿内容が必須になっている（ブランクのまま投稿できないようになっている）
- [x] バリデーションに反した際に、エラーメッセージが表示される
- [x] 未ログイン時には投稿編集画面にアクセスできないようになっている

## テスト
https://i.gyazo.com/3e23e3bc4b73c4c4e794a0353c274d3b.mp4

2020-12-29 06:28 UTC, sdkk1 requested changes
１箇所だけ修正をお願いします！

2020-12-29 06:28 UTC, sdkk1 commented on app/views/posts/edit.html.erb
> +          <span>新規投稿</span>
ここのタイトルを「投稿編集」に修正してください。

2020-12-29 06:41 UTC, katsuokaisao commented
修正致したので再度確認よろしくお願いします！

2020-12-29 07:03 UTC, sdkk1 approved these changes
LGTMです！

2020-12-29 08:09 UTC, Yasunori-aloha requested changes
コード確認しました！
1箇所コメントしていますので、確認をお願いします！

2020-12-29 08:09 UTC, Yasunori-aloha commented on app/controllers/posts_controller.rb
> +    current_user.posts.include?(post) ? @post = post : (redirect_to root_path)
`redirect_to root_path`が何度も記述されているので、メソッドとしてprivate以下に切り出して使用する様にした方がいいかと思います！

2020-12-30 05:03 UTC, Yasunori-aloha approved these changes

2020-12-30 05:04 UTC, Yasunori-aloha commented
LGTMです！

2020-12-30 17:02 UTC, sew-sou19 approved these changes
素晴らしいですー！
一部、メソッドの切り出しについてコメントした部分はありますが、クリティカルな問題ではないのでLGTMです！
（好みで変えても変えなくても大丈夫です）

2020-12-30 17:02 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
> +    current_user.posts.include?(post) ? @post = post : (redirect_to root_path)
1行のシンプルな処理は、わざわざメソッドに切り出す必要はないですー！
この例でいくと、`redirect_to root_path`と`redirect_to_root`で減らせた文字数は`path`の4文字だけです。

また、

- メソッドの内容を確認しに行く手間がある
- メソッドに定義のために3行追加されてる
- 結局`redirect_to_root`を2回記述している（DRY原則に変わりがない）

という状況なので、4文字の削減と比較するとデメリットの方が大きいです。

メソッドを切り出すといいパターン例は

- `before_action`などでまとめて呼び出せる（`@post = Post.find_by(id: params[:id]`など）
- 複数行の処理がある
- 1行の処理でも、記述量が長い（`params.require(:post).permit(:content).merge(user_id: current_user.id)`など）

2020-12-31 00:13 UTC, katsuokaisao commented
> 結局redirect_to_rootを2回記述している（DRY原則に変わりがない）
確かにその通りですね。ご指摘ありがとうございます！

2020-12-31 00:16 UTC, merged